### ISSUE TITLE
How do you use this extension?

### ISSUE THREAD

**Issue by stereokai** [KidkArolis/vscode-healthier#10]
It seems this extension does nothing even though I have healthier installed and listed in package.json...

**Comment by alucryd** [comment]
Looks like it's broken right now:

```
[Error - 11:35:46 AM] Healthier stack trace:
[Error - 11:35:46 AM] TypeError: cli.lintTextSync is not a function
    at validate (/home/alucryd/.vscode-oss/extensions/kidkarolis.vscode-healthier-3.0.0/server/out/healthierServer.js:509:26)
    at /home/alucryd/.vscode-oss/extensions/kidkarolis.vscode-healthier-3.0.0/server/out/healthierServer.js:438:13
```

**Comment by alucryd** [comment]
@KidkArolis Is this plugin abandoned? No pressure, just want to know whether I should look elsewhere for my linting needs.

**Comment by stereokai** [comment]
I dropped it and set up prettier and eslint independently

**Comment by KidkArolis** [comment]
It is being actively used. Please file an issue if you're running into a specific problem.

**Comment by stereokai** [comment]
I filed this issue 5 months, @KidkArolis, just sayin' 😅😋

**Comment by alucryd** [comment]
@KidkArolis Well @stereokai and I are likely running into the same issue, for which I uploaded a stacktrace above. I can open another issue, but I really don't see the point :/

**Comment by KidkArolis** [comment]
Should be fixed now in the latest version of the extension 4.0.0.
