### ISSUE TITLE
Broken on recent VS Code?

### ISSUE THREAD

**Issue by alucryd** [KidkArolis/vscode-healthier#11]
The extension doesn't work here, or on any of my coworkers' stations.

Problem already mentioned on https://github.com/KidkArolis/vscode-healthier/issues/10, and most likely the same issue as the OP issue.

VS Code is VS Codium 1.69.1 running on Arch Linux. Extension installed from the official marketplace.

```
[Error - 11:35:46 AM] Healthier stack trace:
[Error - 11:35:46 AM] TypeError: cli.lintTextSync is not a function
    at validate (/home/alucryd/.vscode-oss/extensions/kidkarolis.vscode-healthier-3.0.0/server/out/healthierServer.js:509:26)
    at /home/alucryd/.vscode-oss/extensions/kidkarolis.vscode-healthier-3.0.0/server/out/healthierServer.js:438:13
```

**Comment by KidkArolis** [comment]
Working on a fix!

**Comment by KidkArolis** [comment]
Should be fixed now in the latest version of the extension 4.0.0. And healthier itself is updated to the latest versions of eslint and of the related packages. The extension should still be compatible with any version of healthier.
