### ISSUE TITLE
Support for fix on save

### ISSUE THREAD

**Issue by ghost** [KidkArolis/vscode-healthier#7]
There's no current support for _fix on save_, is there? If not, it would be a great feature.

```
 "editor.codeActionsOnSave": {
    "source.fixAll.healthier": true
  }
```
By the way, thanks very much for making this, Standard + Prettier = not easy!

**Comment by KidkArolis** [comment]
In practise, I never need to run healthier --fix.. Well, --fix was only re-added in the most recent version, I think, so maybe it would be helpful.. That's because prettier fixes most things.

But fair enough, fix on save would make sense to add and should be the default, perhaps.

**Comment by ghost** [comment]
True, Prettier does fix _most_ things. One thing that Prettier doesn't (can't) fix, for example,  is conversion of `let` to `const` where applicable. But, who's to say one is even using Prettier? 

> Because Healthier is only concerned with code quality linting, it means you can use any code formatter ...

Which leads to another question: Do you have any plans to integrate Prettier directly in Healthier? 

One devDependency, one editor extension, zero config, would be the gold standard. All ESLint based formatting tools, such as Standard itself, XO, etc. are quirky and fall short of Prettier in my experience.

And....It looks like Prettier may add options, bringing it to greater parity with Standard, in upcoming releases (https://github.com/prettier/prettier/issues/3847, https://github.com/prettier/prettier/issues/3845#). Maybe one day Standard and Prettier will work together so they can both finally achieve what they set out to do. 🤞 They are, ironically, the ones holding each other up in this case.

**Comment by ghost** [comment]
Update:

I just read in Healthier's changelog that Prettier was previously integrated in Healthier, as well the reasons for removing it. So all of that answers my question and I guess Healthier's approach is the best way to go given the current state of things.
